name: Check Files
on: [push] #Runs when you push code

jobs:
  verify_files:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout code
       uses: actions/checkout@v4

      -name: List files (debug)
       run: ls-la
